using Microsoft.Extensions.DependencyInjection;

namespace JR.CodeGenerator.ViewModels;

/// <summary>
/// 
/// </summary>
/// <autogeneratedoc />
public class ViewModelLocator
{
    /// <summary>
    /// Gets the main view model.
    /// </summary>
    /// <value>
    /// The main view model.
    /// </value>
    /// <autogeneratedoc />
    public MainViewModel MainViewModel => App.ServiceProvider.GetRequiredService<MainViewModel>();
}