using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JR.CodeGenerator.Models
{
    /// <summary>
    /// DataBaseDto
    /// </summary>
    /// <autogeneratedoc />
    public class DataBase
    {
        public DataBase(int id, string name )
        {
            Id = id;
            Name = name;
        }
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        /// <autogeneratedoc />
        public int Id { get; private set; }
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        /// <autogeneratedoc />
        public string Name { get; private set; }
    }
}
