using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JR.CodeGenerator.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class DataGeneral
    {
        /// <summary>
        /// Gets or sets the empresa.
        /// </summary>
        /// <value>
        /// The empresa.
        /// </value>
        /// <autogeneratedoc />
        public string Empresa { get; set; }
        /// <summary>
        /// Gets or sets the autor.
        /// </summary>
        /// <value>
        /// The autor.
        /// </value>
        /// <autogeneratedoc />
        public string Autor { get; set; }
        /// <summary>
        /// Gets or sets the name space.
        /// </summary>
        /// <value>
        /// The name space.
        /// </value>
        /// <autogeneratedoc />
        public string NameSpace { get; set; }

        /// <summary>
        /// Gets or sets the path.
        /// </summary>
        /// <value>
        /// The path.
        /// </value>
        /// <autogeneratedoc />
        public string Path { get; set; }

        /// <summary>
        /// Converts to titlecase.
        /// </summary>
        /// <value>
        ///   <c>true</c> if [to title case]; otherwise, <c>false</c>.
        /// </value>
        /// <autogeneratedoc />
        public bool ToTitleCase { get; set; }
    }
}
