using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;

namespace JR.CodeGenerator.Models
{
    /// <summary>
    /// InfoCampo
    /// </summary>
    /// <autogeneratedoc />
    public class InfoCampo
    {
        public string Table_Catalog { get; set; }
        public string Table_Schema { get; set; }
        public string Table_Name { get; set; }
        public string Column_Name { get; set; }
        public int Ordinal_Position { get; set; }
        public string Column_Default { get; set; }
        public string Is_Nullable { get; set; }
        public string Data_Type { get; set; }
        public int? Character_Maximum_Length { get; set; }
        public int? Character_Octet_Length { get; set; }
        public int? Numeric_Precision { get; set; }
        public int? Numeric_Precision_Radix { get; set; }
        public int? Numeric_Scale { get; set; }
        public int? Datetime_Precision { get; set; }
        public string Character_Set_Catalog { get; set; }
        public string Character_Set_Schema { get; set; }
        public string Character_Set_Name { get; set; }
        public string Collation_Catalog { get; set; }
        public string Collation_Schema { get; set; }
        public string Collation_Name { get; set; }
        public string Domain_Catalog { get; set; }
        public string Domain_Schema { get; set; }
        public string Domain_Name { get; set; }
        public int Column_Length { get; set; }
        public int Is_Computed { get; set; }
        public int Is_Identity { get; set; }
        public int Is_Rowguidcol { get; set; }
        public bool Clave_Primaria { get; set; }
        public string Campo_Descripcion { get; set; }


    }
}
