using CommunityToolkit.Mvvm.ComponentModel;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace JR.CodeGenerator.Models
{
    /// <summary>
    /// TableViewDto
    /// </summary>
    public partial class TableView : ObservableObject
    {
        private bool isSelected;

        /// <summary>
        /// Initializes a new instance of the <see cref="TableView" /> class.
        /// </summary>
        public TableView()
        {
            Children = new List<TableView>();           
        }

        public string Name { get; set; } = string.Empty;
        public string Schema { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        /// <autogeneratedoc />
        public string FullName { get => String.IsNullOrWhiteSpace(Schema) ? Name : $"{Schema}.{Name}"; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is selected.
        /// </summary>
        /// <value>
        ///   <c>true</c> if this instance is selected; otherwise, <c>false</c>.
        /// </value>
        /// <autogeneratedoc />
        public bool IsSelected
        {
            get => isSelected;
            set
            {
                if (isSelected != value)
                {
                    if (Name == "Tablas" || Name == "Vistas")
                    {
                        foreach (var item in Children)
                        {
                            item.IsSelected = value;
                        }
                    }
                }

                SetProperty(ref isSelected, value);

            }
        }
        
        /// <summary>
        /// Gets or sets the children.
        /// </summary>
        /// <value>
        /// The children.
        /// </value>
        /// <autogeneratedoc />
        public List<TableView> Children { get; set; }

        /// <summary>
        /// Gets or sets the image URI.
        /// </summary>
        /// <value>
        /// The image URI.
        /// </value>
        /// <autogeneratedoc />
        public string ImageUri { get; set; }

        /// <summary>
        /// Tos the string.
        /// </summary>
        /// <returns>
        /// A string.
        /// </returns>
        public override string ToString()
        {
            return (FullName == "Tablas" || FullName == "Vistas") ? $"{Name} ({Children.Count})" : FullName;
        }
    }
}
